# This workflow to test building Kata Containers pause image.
# Validates the build works on both container and VM runners.
# Issue: https://github.com/IBM/actionspz/issues/43
name: kata-test

on:
  workflow_dispatch:

jobs:
  kata-test:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-22.04-s390x
          - ubuntu-22.04-s390x-vm
          - ubuntu-24.04-s390x
          - ubuntu-24.04-s390x-vm
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 10

    steps:
      - name: Build pause-image
        run: |
          git clone https://github.com/kata-containers/kata-containers.git
          cd kata-containers
          sudo make pause-image-tarball-build
